# Learning: Pandas (2)

This jupyter notebook gives introduction to Python pandas package and its use in data science.

References:

Boris Paskhaver, Data Analysis with Pandas and Python, Udemy

The packages used in this tutorial are as follows. Notice that to import the packages, they must have been installed in the environment where this jupyter notebook is running.

In [1]:
import numpy as np
import pandas as pd

print("Numpy version: {}".format(np.__version__))
print("Panda version: {}".format(pd.__version__))

Numpy version: 1.23.5
Panda version: 1.5.2

## Import Data
Pandas provides flexible data import approaches from variety of data resources, including csv, excel, clipboard, json, html, xml, latex table, and many more. Details can be found [here](https://pandas.pydata.org/docs/reference/io.html "https://pandas.pydata.org/docs/reference/io.html"). 

Pandas privede `.read_csv()` method that reads a csv file into a data frame. Its synax is given below. More details about `.read_csv()` are given [here](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html "https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html").
```python
pandas.read_csv(filepath_or_buffer, *, sep=_NoDefault.no_default, delimiter=None, header='infer', names=_NoDefault.no_default, index_col=None, usecols=None, squeeze=None, prefix=_NoDefault.no_default, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=None, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, error_bad_lines=None, warn_bad_lines=None, on_bad_lines=None, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None, storage_options=None)
```

An example is given below. For this example, `pokemon.csv` from [here](https://www.kaggle.com/datasets/abcsds/pokemon "https://www.kaggle.com/datasets/abcsds/pokemon") is used.

In [2]:
pokemon_df = pd.read_csv("pokemon.csv")
pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

It is possible to read a single column from the csv, and make a series from it. An example is given below.

In [3]:
pokemon_series = pd.read_csv("pokemon.csv",usecols = ["Name"]).squeeze("columns").copy()
pokemon_series

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

Another example of importing google stock price is given below. The google stock price is downloaded from [here](https://www.kaggle.com/datasets/akpmpr/google-stock-price-all-time "https://www.kaggle.com/datasets/akpmpr/google-stock-price-all-time").

In [4]:
google_stock_df = pd.read_csv("google_stock.csv")
print(google_stock_df)

            Date         High          Low         Open        Close  \
0     2004-08-19    51.835709    47.800831    49.813290    49.982655
1     2004-08-20    54.336334    50.062355    50.316402    53.952770
2     2004-08-23    56.528118    54.321388    55.168217    54.495735
3     2004-08-24    55.591629    51.591621    55.412300    52.239197
4     2004-08-25    53.798351    51.746044    52.284027    52.802086
...          ...          ...          ...          ...          ...
4312  2021-10-05  2747.239990  2680.000000  2680.000000  2723.540039
4313  2021-10-06  2757.040039  2689.729980  2692.510010  2747.080078
4314  2021-10-07  2803.089111  2771.260010  2777.260010  2783.709961
4315  2021-10-08  2806.340088  2788.586914  2798.120117  2801.120117
4316  2021-10-11  2815.272949  2776.129883  2796.000000  2776.949951

          Volume    Adj Close
0     44871361.0    49.982655
1     22942874.0    53.952770
2     18342897.0    54.495735
3     15319808.0    52.239197
4      9232276.0    52.802086
...          ...          ...
4312   1206300.0  2723.540039
4313    988200.0  2747.080078
4314    912500.0  2783.709961
4315    946200.0  2801.120117
4316    828700.0  2776.949951

[4317 rows x 7 columns]

In [5]:
google_stock_series = pd.read_csv("google_stock.csv", usecols = ["Close"]).squeeze("columns").copy()
google_stock_series

0         49.982655
1         53.952770
2         54.495735
3         52.239197
4         52.802086
           ...
4312    2723.540039
4313    2747.080078
4314    2783.709961
4315    2801.120117
4316    2776.949951
Name: Close, Length: 4317, dtype: float64

When reading a csv file, it is possible to specify the a column as the index column. If the index column is not specified, pandas creates an additional numerical column 0, 1, 2, ..., as the index column, as shown before.

An example is given below.

In [6]:
pokemon_series_ind_name = pd.read_csv("pokemon.csv", index_col = "Name")
pokemon_series_ind_name

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,719,Rock,Fairy,600,50,100,150,100,150,50,6,True
DiancieMega Diancie,719,Rock,Fairy,700,50,160,110,160,110,110,6,True
HoopaHoopa Confined,720,Psychic,Ghost,600,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,720,Psychic,Dark,680,80,160,60,170,130,80,6,True
Volcanion,721,Fire,Water,600,80,110,120,130,90,70,6,True